export const testCardSet = [
  { id: 0, imgName: 'monkey.jpg', setId: 0, isGuessed: false, isTurned: false, },
  { id: 1, imgName: 'monkey.jpg', setId: 0, isGuessed: false, isTurned: false, },
  { id: 2, imgName: 'beach.jpg', setId: 1, isGuessed: false, isTurned: false, },
  { id: 3, imgName: 'beach.jpg', setId: 1, isGuessed: false, isTurned: false, },
  { id: 4, imgName: 'bout.jpg', setId: 2, isGuessed: false, isTurned: false, },
  { id: 5, imgName: 'bout.jpg', setId: 2, isGuessed: false, isTurned: false, },
  { id: 6, imgName: 'mount.jpg', setId: 3, isGuessed: false, isTurned: false, },
  { id: 7, imgName: 'mount.jpg', setId: 3, isGuessed: false, isTurned: false, },
  { id: 8, imgName: 'road.jpg', setId: 4, isGuessed: false, isTurned: false, },
  { id: 9, imgName: 'road.jpg', setId: 4, isGuessed: false, isTurned: false, },
  { id: 10, imgName: 'sea.jpg', setId: 5, isGuessed: false, isTurned: false, },
  { id: 11, imgName: 'sea.jpg', setId: 5, isGuessed: false, isTurned: false, },
  { id: 12, imgName: 'sity.jpg', setId: 6, isGuessed: false, isTurned: false, },
  { id: 13, imgName: 'sity.jpg', setId: 6, isGuessed: false, isTurned: false, },
  { id: 14, imgName: 'sky.jpg', setId: 7, isGuessed: false, isTurned: false, },
  { id: 15, imgName: 'sky.jpg', setId: 7, isGuessed: false, isTurned: false, },
  { id: 16, imgName: 'test.jpg', setId: 8, isGuessed: false, isTurned: false, },
  { id: 17, imgName: 'test.jpg', setId: 8, isGuessed: false, isTurned: false, },
];

